INCLUDEPATH += $$PWD

HEADERS += \
    $$PWD/poseviewer/renderframegraph.hpp \
    $$PWD/rendering/arcballrotationhandler.hpp \
    $$PWD/rendering/gizmo/arrowtranslationhandle.hpp \
    $$PWD/rendering/gizmo/flatmaterial.hpp \
    $$PWD/rendering/gizmo/handle.hpp \
    $$PWD/rendering/gizmo/planetranslationhandle.hpp \
    $$PWD/rendering/gizmo/qt3dgizmo.hpp \
    $$PWD/rendering/gizmo/qt3dgizmo_p.hpp \
    $$PWD/rendering/gizmo/rotationhandle.hpp \
    $$PWD/rendering/modificationhandler.hpp \
    $$PWD/rendering/outlinematerial.hpp \
    $$PWD/rendering/qt3dwidget.hpp \
    $$PWD/rendering/translationhandler.hpp \
    $$PWD/poseviewer/mousecoordinatesmodificationeventfilter.hpp \
    $$PWD/poseviewer/undomousecoordinatesmodificationeventfilter.hpp \
    $$PWD/settings/settingsloadsavepage.hpp \
    $$PWD/splashscreen/splashscreen.hpp \
    $$PWD/settings/settingspathspage.hpp \
    $$PWD/gallery/loadingiconmodel.hpp \
    $$PWD/gallery/galleryobjectmodels.hpp \
    $$PWD/misc/displayhelper.hpp \
    $$PWD/mainwindow.hpp \
    $$PWD/breadcrumb/breadcrumbview.hpp \
    $$PWD/gallery/gallery.hpp \
    $$PWD/gallery/galleryimagemodel.hpp \
    $$PWD/gallery/galleryobjectmodelmodel.hpp \
    $$PWD/gallery/iconexpandinglistview.hpp \
    $$PWD/rendering/backgroundimagerenderable.hpp \
    $$PWD/settings/settingsdialog.hpp \
    $$PWD/settings/settingssegmentationcodespage.hpp \
    $$PWD/settings/settingsinterfacepage.hpp \
    $$PWD/poseviewer/poseviewer.hpp \
    $$PWD/poseviewer/poseviewer3dwidget.hpp \
    $$PWD/poseeditor/poseeditor.hpp \
    $$PWD/poseeditor/poseeditor3dwidget.hpp \
    $$PWD/gallery/resizeimagesrunnable.hpp \
    $$PWD/rendering/offscreenengine.hpp \
    $$PWD/rendering/poserenderable.hpp \
    $$PWD/rendering/objectmodelrenderable.hpp \
    $$PWD/rendering/texturerendertarget.hpp \
    $$PWD/rendering/clickvisualizationmaterial.hpp \
    $$PWD/rendering/clickvisualizationrenderable.hpp \
    $$PWD/tutorialscreen/tutorialscreen.hpp

SOURCES += \
    $$PWD/poseviewer/renderframegraph.cpp \
    $$PWD/rendering/arcballrotationhandler.cpp \
    $$PWD/rendering/gizmo/arrowtranslationhandle.cpp \
    $$PWD/rendering/gizmo/flatmaterial.cpp \
    $$PWD/rendering/gizmo/handle.cpp \
    $$PWD/rendering/gizmo/planetranslationhandle.cpp \
    $$PWD/rendering/gizmo/qt3dgizmo.cpp \
    $$PWD/rendering/gizmo/rotationhandle.cpp \
    $$PWD/rendering/modificationhandler.cpp \
    $$PWD/rendering/outlinematerial.cpp \
    $$PWD/rendering/qt3dwidget.cpp \
    $$PWD/rendering/translationhandler.cpp \
    $$PWD/poseviewer/mousecoordinatesmodificationeventfilter.cpp \
    $$PWD/poseviewer/undomousecoordinatesmodificationeventfilter.cpp \
    $$PWD/settings/settingsloadsavepage.cpp \
    $$PWD/splashscreen/splashscreen.cpp \
    $$PWD/settings/settingspathspage.cpp \
    $$PWD/mainwindow.cpp \
    $$PWD/breadcrumb/breadcrumbview.cpp \
    $$PWD/settings/settingsdialog.cpp \
    $$PWD/settings/settingssegmentationcodespage.cpp \
    $$PWD/settings/settingsinterfacepage.cpp \
    $$PWD/poseviewer/poseviewer.cpp \
    $$PWD/poseviewer/poseviewer3dwidget.cpp \
    $$PWD/poseeditor/poseeditor.cpp \
    $$PWD/poseeditor/poseeditor3dwidget.cpp \
    $$PWD/misc/displayhelper.cpp \
    $$PWD/gallery/loadingiconmodel.cpp \
    $$PWD/gallery/galleryobjectmodels.cpp \
    $$PWD/gallery/gallery.cpp \
    $$PWD/gallery/galleryimagemodel.cpp \
    $$PWD/gallery/galleryobjectmodelmodel.cpp \
    $$PWD/gallery/iconexpandinglistview.cpp \
    $$PWD/gallery/resizeimagesrunnable.cpp \
    $$PWD/rendering/offscreenengine.cpp \
    $$PWD/rendering/texturerendertarget.cpp \
    $$PWD/rendering/backgroundimagerenderable.cpp \
    $$PWD/rendering/poserenderable.cpp \
    $$PWD/rendering/objectmodelrenderable.cpp \
    $$PWD/rendering/clickvisualizationmaterial.cpp \
    $$PWD/rendering/clickvisualizationrenderable.cpp \
    $$PWD/tutorialscreen/tutorialscreen.cpp

FORMS += \
    $$PWD/settings/settingsloadsavepage.ui \
    $$PWD/breadcrumb/breadcrumbview.ui \
    $$PWD/settings/settingspathspage.ui \
    $$PWD/mainwindow.ui \
    $$PWD/gallery/gallery.ui \
    $$PWD/settings/settingsdialog.ui \
    $$PWD/settings/settingsinterfacepage.ui \
    $$PWD/settings/settingssegmentationcodespage.ui \
    $$PWD/poseviewer/poseviewer.ui \
    $$PWD/poseeditor/poseeditor.ui \
